### ISSUE TITLE
Publish to pypi?

### ISSUE THREAD

**Issue by mwarkentin** [z0ph/aa-policy-validator#1]
Hey, this looks great! Any plans to publish to pypi so it's just a pip install away?

**Comment by z0ph** [comment]
Hey @mwarkentin,

Thanks for the advice, I've publish the package on PyPI: https://pypi.org/project/aa-policy-validator/

I've also updated the `README.md` accordingly.

**Comment by mwarkentin** [comment]
Thanks!
